title: Oxford University Gliding Club
baseurl: "/ougc.org"
tagline: Take Flight Today
description: Oxford University Gliding Club
cover: cover.jpg

categories_path: /categories/
tags_path: /tags/

plugins:
  - jekyll-remote-theme
remote_theme: vfvong/jekyll-theme-quartz
