title: Oxford University Gliding Club
baseurl: "/ougc.org"
tagline: Take Flight Today
description: Oxford University Gliding Club
cover: assets/images/covers/cover.webp

categories_path: /categories/
tags_path: /tags/
markdown: kramdown
plugins:
  - jekyll-remote-theme
remote_theme: vfvong/jekyll-theme-quartz
